### ISSUE TITLE
fmradio causes rebooting.

### ISSUE THREAD

**Issue by kodhh** [Saikrishna1504/kernel_xiaomi_mt6785#1]
but I solved it, reference my patch [workout fmradio](https://github.com/Saikrishna1504/kernel_xiaomi_mt6785/commit/cdd13ca4c8ee6d7633198b3af6f259d65989a60c)

**Comment by kodhh** [comment]
> but I solved it, reference my patch [workout fmradio](https://github.com/Saikrishna1504/kernel_xiaomi_mt6785/commit/cdd13ca4c8ee6d7633198b3af6f259d65989a60c)

[reference](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/begonia-r-oss/drivers/misc/mediatek/connectivity/Makefile)

**Comment by Saikrishna1504** [comment]
Tested ?

**Comment by kodhh** [comment]
Tested! On android 13, if it had used these kernel, it would reboot either while opening fm. It is fixed, until the fmradio intergraded. And the fm dose work fined.

**Comment by Saikrishna1504** [comment]
Cool .. pick properly and make a pr if possible. I will test it out and merge
